version: "3.7"
services:
  order-db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=order
      - MYSQL_ROOT_PASSWORD=root-pass
      - MYSQL_USER=order-svc
      - MYSQL_PASSWORD=order-pass
      - TZ=UTC
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - ./mysql:/var/lib/mysql